.TH "client/src Directory Reference" 3 "Tue Nov 3 2015" "Version 0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBtests\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient\&.c\fP"
.br
.RI "\fIclient header client prototypes \fP"
.ti -1c
.RI "file \fBclient\&.h\fP"
.br
.in -1c
