.TH "common Directory Reference" 3 "Tue Nov 3 2015" "Version 0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdefines\&.c\fP"
.br
.RI "\fIdefines common definitions \fP"
.ti -1c
.RI "file \fBdefines\&.h\fP"
.br
.RI "\fIdefines common definitions \fP"
.ti -1c
.RI "file \fBnet\&.c\fP"
.br
.RI "\fInetworking common net definitions \fP"
.ti -1c
.RI "file \fBnet\&.h\fP"
.br
.RI "\fInetworking common net definitions \fP"
.ti -1c
.RI "file \fBsensors\&.c\fP"
.br
.RI "\fIsensors common mock sensors definitions \fP"
.ti -1c
.RI "file \fBsensors\&.h\fP"
.br
.RI "\fImock sensors common mock sensors definitions \fP"
.ti -1c
.RI "file \fBxml\&.c\fP"
.br
.RI "\fIxml xml parsing helpers \fP"
.ti -1c
.RI "file \fBxml\&.h\fP"
.br
.RI "\fIxml xml parsing helpers \fP"
.in -1c
