.TH "client/src/client.c" 3 "Tue Nov 3 2015" "Version 0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client/src/client.c \- 
client header client prototypes  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include 'net\&.h'\fP
.br
\fC#include 'sensors\&.h'\fP
.br
\fC#include 'xml\&.h'\fP
.br
\fC#include 'client\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
client header client prototypes 


.PP
\fBAuthor:\fP
.RS 4
Claudio Neto
.RE
.PP
\fBDate:\fP
.RS 4
3/11/2015 
.RE
.PP

.PP
Definition in file \fBclient\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 31 of file client\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
