.TH "common/defines.c" 3 "Tue Nov 3 2015" "Version 0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/defines.c \- 
.PP
defines common definitions  

.SH SYNOPSIS
.br
.PP
\fC#include 'defines\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char const * \fBrequest_str\fP []"
.br
.ti -1c
.RI "const char const * \fBbrightness_str\fP []"
.br
.ti -1c
.RI "const char const * \fBsensor_str\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
defines common definitions 


.PP
\fBAuthor:\fP
.RS 4
Claudio Neto
.RE
.PP
\fBDate:\fP
.RS 4
3/11/2015 
.RE
.PP

.PP
Definition in file \fBdefines\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const char const* brightness_str[]"
\fBInitial value:\fP
.PP
.nf
= {
    "dark",
    "average",
    "bright",
    "max_brightness"
}
.fi
.PP
Definition at line 19 of file defines\&.c\&.
.SS "const char const* request_str[]"
\fBInitial value:\fP
.PP
.nf
= {
    "config",
    "retrieve",
    "update"
}
.fi
.PP
Definition at line 13 of file defines\&.c\&.
.SS "const char const* sensor_str[]"
\fBInitial value:\fP
.PP
.nf
= {
    "battery",
    "brightness",
    "humidity",
    "noise",
    "personsPassed",
    "temperature",
    "max_sensors"
}
.fi
.PP
Definition at line 26 of file defines\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
