.TH "common/net.c" 3 "Tue Nov 3 2015" "Version 0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/net.c \- 
.PP
networking common net definitions  

.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'net\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadSocket\fP (int sock, char recvline[])"
.br
.ti -1c
.RI "int \fBwriteSocket\fP (int sock, char sendline[])"
.br
.ti -1c
.RI "int \fBconnectToServer\fP (void *sock_desc)"
.br
.in -1c
.SH "Detailed Description"
.PP 
networking common net definitions 


.PP
\fBAuthor:\fP
.RS 4
Claudio Neto
.RE
.PP
\fBDate:\fP
.RS 4
3/11/2015 
.RE
.PP

.PP
Definition in file \fBnet\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int connectToServer (void *sock_desc)"
Connect to Sever 
.PP
Definition at line 85 of file net\&.c\&.
.SS "int readSocket (intsock, charrecvline[])"
Read from Socket 
.PP
Definition at line 24 of file net\&.c\&.
.SS "int writeSocket (intsock, charsendline[])"
Write to socket 
.PP
Definition at line 58 of file net\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
