.TH "Reading_t" 3 "Tue Nov 3 2015" "Version 0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reading_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <defines\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBelapsed\fP"
.br
.ti -1c
.RI "int \fBinterval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file defines\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int elapsed"

.PP
Definition at line 68 of file defines\&.h\&.
.SS "int interval"

.PP
Definition at line 69 of file defines\&.h\&.
.SS "int value"

.PP
Definition at line 67 of file defines\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
