.TH "server/src/tests/test.c" 3 "Tue Nov 3 2015" "Version 0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server/src/tests/test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'test\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'ezxml\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxml_test\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void xml_test ()"

.PP
Definition at line 15 of file test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
