/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockxml.h"

typedef struct _CMOCK_buildReplyXML_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  char* Expected_recvline;
  char* Expected_sendline;
  size_t Expected_read_size;

} CMOCK_buildReplyXML_CALL_INSTANCE;

typedef struct _CMOCK_buildRequestXML_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  eRequest Expected_req;
  char* Expected_sendline;

} CMOCK_buildRequestXML_CALL_INSTANCE;

typedef struct _CMOCK_writeConfig_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_writeConfig_CALL_INSTANCE;

typedef struct _CMOCK_readConfig_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_readConfig_CALL_INSTANCE;

static struct MockxmlInstance
{
  CMOCK_MEM_INDEX_TYPE buildReplyXML_CallInstance;
  CMOCK_MEM_INDEX_TYPE buildRequestXML_CallInstance;
  CMOCK_MEM_INDEX_TYPE writeConfig_CallInstance;
  CMOCK_MEM_INDEX_TYPE readConfig_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockxml_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.buildReplyXML_CallInstance, cmock_line, "Function 'buildReplyXML' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.buildRequestXML_CallInstance, cmock_line, "Function 'buildRequestXML' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.writeConfig_CallInstance, cmock_line, "Function 'writeConfig' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.readConfig_CallInstance, cmock_line, "Function 'readConfig' called less times than expected.");
}

void Mockxml_Init(void)
{
  Mockxml_Destroy();
}

void Mockxml_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint16_t buildReplyXML(char* recvline, char* sendline, size_t read_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_buildReplyXML_CALL_INSTANCE* cmock_call_instance = (CMOCK_buildReplyXML_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.buildReplyXML_CallInstance);
  Mock.buildReplyXML_CallInstance = CMock_Guts_MemNext(Mock.buildReplyXML_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'buildReplyXML' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_recvline, recvline, cmock_line, "Function 'buildReplyXML' called with unexpected value for argument 'recvline'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_sendline, sendline, cmock_line, "Function 'buildReplyXML' called with unexpected value for argument 'sendline'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_read_size), (void*)(&read_size), sizeof(size_t), cmock_line, "Function 'buildReplyXML' called with unexpected value for argument 'read_size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_buildReplyXML(CMOCK_buildReplyXML_CALL_INSTANCE* cmock_call_instance, char* recvline, char* sendline, size_t read_size)
{
  cmock_call_instance->Expected_recvline = recvline;
  cmock_call_instance->Expected_sendline = sendline;
  memcpy(&cmock_call_instance->Expected_read_size, &read_size, sizeof(size_t));
}

void buildReplyXML_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* recvline, char* sendline, size_t read_size, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_buildReplyXML_CALL_INSTANCE));
  CMOCK_buildReplyXML_CALL_INSTANCE* cmock_call_instance = (CMOCK_buildReplyXML_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.buildReplyXML_CallInstance = CMock_Guts_MemChain(Mock.buildReplyXML_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_buildReplyXML(cmock_call_instance, recvline, sendline, read_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint16_t buildRequestXML(eRequest req, char* sendline)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_buildRequestXML_CALL_INSTANCE* cmock_call_instance = (CMOCK_buildRequestXML_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.buildRequestXML_CallInstance);
  Mock.buildRequestXML_CallInstance = CMock_Guts_MemNext(Mock.buildRequestXML_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'buildRequestXML' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_req), (void*)(&req), sizeof(eRequest), cmock_line, "Function 'buildRequestXML' called with unexpected value for argument 'req'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_sendline, sendline, cmock_line, "Function 'buildRequestXML' called with unexpected value for argument 'sendline'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_buildRequestXML(CMOCK_buildRequestXML_CALL_INSTANCE* cmock_call_instance, eRequest req, char* sendline)
{
  memcpy(&cmock_call_instance->Expected_req, &req, sizeof(eRequest));
  cmock_call_instance->Expected_sendline = sendline;
}

void buildRequestXML_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, eRequest req, char* sendline, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_buildRequestXML_CALL_INSTANCE));
  CMOCK_buildRequestXML_CALL_INSTANCE* cmock_call_instance = (CMOCK_buildRequestXML_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.buildRequestXML_CallInstance = CMock_Guts_MemChain(Mock.buildRequestXML_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_buildRequestXML(cmock_call_instance, req, sendline);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int writeConfig(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_writeConfig_CALL_INSTANCE* cmock_call_instance = (CMOCK_writeConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.writeConfig_CallInstance);
  Mock.writeConfig_CallInstance = CMock_Guts_MemNext(Mock.writeConfig_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'writeConfig' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void writeConfig_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_writeConfig_CALL_INSTANCE));
  CMOCK_writeConfig_CALL_INSTANCE* cmock_call_instance = (CMOCK_writeConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.writeConfig_CallInstance = CMock_Guts_MemChain(Mock.writeConfig_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int readConfig(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_readConfig_CALL_INSTANCE* cmock_call_instance = (CMOCK_readConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.readConfig_CallInstance);
  Mock.readConfig_CallInstance = CMock_Guts_MemNext(Mock.readConfig_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'readConfig' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void readConfig_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_readConfig_CALL_INSTANCE));
  CMOCK_readConfig_CALL_INSTANCE* cmock_call_instance = (CMOCK_readConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.readConfig_CallInstance = CMock_Guts_MemChain(Mock.readConfig_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

