/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKXML_H
#define _MOCKXML_H

#include "xml.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockxml_Init(void);
void Mockxml_Destroy(void);
void Mockxml_Verify(void);




#define buildReplyXML_ExpectAndReturn(recvline, sendline, read_size, cmock_retval) buildReplyXML_CMockExpectAndReturn(__LINE__, recvline, sendline, read_size, cmock_retval)
void buildReplyXML_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* recvline, char* sendline, size_t read_size, uint16_t cmock_to_return);
#define buildRequestXML_ExpectAndReturn(req, sendline, cmock_retval) buildRequestXML_CMockExpectAndReturn(__LINE__, req, sendline, cmock_retval)
void buildRequestXML_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, eRequest req, char* sendline, uint16_t cmock_to_return);
#define writeConfig_ExpectAndReturn(cmock_retval) writeConfig_CMockExpectAndReturn(__LINE__, cmock_retval)
void writeConfig_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define readConfig_ExpectAndReturn(cmock_retval) readConfig_CMockExpectAndReturn(__LINE__, cmock_retval)
void readConfig_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);

#endif
