/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocksensors.h"

typedef struct _CMOCK_getSensorReadingStr_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  eSensor Expected_s;
  char* Expected_buffer;

} CMOCK_getSensorReadingStr_CALL_INSTANCE;

typedef struct _CMOCK_newMeasurement_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  eSensor Expected_s;

} CMOCK_newMeasurement_CALL_INSTANCE;

typedef struct _CMOCK_generateMeasurements_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;

} CMOCK_generateMeasurements_CALL_INSTANCE;

static struct MocksensorsInstance
{
  CMOCK_MEM_INDEX_TYPE getSensorReadingStr_CallInstance;
  CMOCK_MEM_INDEX_TYPE newMeasurement_CallInstance;
  CMOCK_MEM_INDEX_TYPE generateMeasurements_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksensors_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.getSensorReadingStr_CallInstance, cmock_line, "Function 'getSensorReadingStr' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.newMeasurement_CallInstance, cmock_line, "Function 'newMeasurement' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.generateMeasurements_CallInstance, cmock_line, "Function 'generateMeasurements' called less times than expected.");
}

void Mocksensors_Init(void)
{
  Mocksensors_Destroy();
}

void Mocksensors_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint16_t getSensorReadingStr(eSensor s, char* buffer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getSensorReadingStr_CALL_INSTANCE* cmock_call_instance = (CMOCK_getSensorReadingStr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getSensorReadingStr_CallInstance);
  Mock.getSensorReadingStr_CallInstance = CMock_Guts_MemNext(Mock.getSensorReadingStr_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'getSensorReadingStr' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_s), (void*)(&s), sizeof(eSensor), cmock_line, "Function 'getSensorReadingStr' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'getSensorReadingStr' called with unexpected value for argument 'buffer'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_getSensorReadingStr(CMOCK_getSensorReadingStr_CALL_INSTANCE* cmock_call_instance, eSensor s, char* buffer)
{
  memcpy(&cmock_call_instance->Expected_s, &s, sizeof(eSensor));
  cmock_call_instance->Expected_buffer = buffer;
}

void getSensorReadingStr_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, eSensor s, char* buffer, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getSensorReadingStr_CALL_INSTANCE));
  CMOCK_getSensorReadingStr_CALL_INSTANCE* cmock_call_instance = (CMOCK_getSensorReadingStr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getSensorReadingStr_CallInstance = CMock_Guts_MemChain(Mock.getSensorReadingStr_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_getSensorReadingStr(cmock_call_instance, s, buffer);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int newMeasurement(eSensor s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_newMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_newMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.newMeasurement_CallInstance);
  Mock.newMeasurement_CallInstance = CMock_Guts_MemNext(Mock.newMeasurement_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'newMeasurement' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_s), (void*)(&s), sizeof(eSensor), cmock_line, "Function 'newMeasurement' called with unexpected value for argument 's'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_newMeasurement(CMOCK_newMeasurement_CALL_INSTANCE* cmock_call_instance, eSensor s)
{
  memcpy(&cmock_call_instance->Expected_s, &s, sizeof(eSensor));
}

void newMeasurement_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, eSensor s, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_newMeasurement_CALL_INSTANCE));
  CMOCK_newMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_newMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.newMeasurement_CallInstance = CMock_Guts_MemChain(Mock.newMeasurement_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_newMeasurement(cmock_call_instance, s);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint16_t generateMeasurements(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_generateMeasurements_CALL_INSTANCE* cmock_call_instance = (CMOCK_generateMeasurements_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.generateMeasurements_CallInstance);
  Mock.generateMeasurements_CallInstance = CMock_Guts_MemNext(Mock.generateMeasurements_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'generateMeasurements' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void generateMeasurements_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_generateMeasurements_CALL_INSTANCE));
  CMOCK_generateMeasurements_CALL_INSTANCE* cmock_call_instance = (CMOCK_generateMeasurements_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.generateMeasurements_CallInstance = CMock_Guts_MemChain(Mock.generateMeasurements_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

