/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSENSORS_H
#define _MOCKSENSORS_H

#include "sensors.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocksensors_Init(void);
void Mocksensors_Destroy(void);
void Mocksensors_Verify(void);




#define getSensorReadingStr_ExpectAndReturn(s, buffer, cmock_retval) getSensorReadingStr_CMockExpectAndReturn(__LINE__, s, buffer, cmock_retval)
void getSensorReadingStr_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, eSensor s, char* buffer, uint16_t cmock_to_return);
#define newMeasurement_ExpectAndReturn(s, cmock_retval) newMeasurement_CMockExpectAndReturn(__LINE__, s, cmock_retval)
void newMeasurement_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, eSensor s, int cmock_to_return);
#define generateMeasurements_ExpectAndReturn(cmock_retval) generateMeasurements_CMockExpectAndReturn(__LINE__, cmock_retval)
void generateMeasurements_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);

#endif
