/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKNET_H
#define _MOCKNET_H

#include "net.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocknet_Init(void);
void Mocknet_Destroy(void);
void Mocknet_Verify(void);




#define readSocket_ExpectAndReturn(sock, recvline, cmock_retval) readSocket_CMockExpectAndReturn(__LINE__, sock, recvline, cmock_retval)
void readSocket_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sock, char* recvline, int cmock_to_return);
#define writeSocket_ExpectAndReturn(sock, sendline, cmock_retval) writeSocket_CMockExpectAndReturn(__LINE__, sock, sendline, cmock_retval)
void writeSocket_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sock, char* sendline, int cmock_to_return);
#define connectToServer_ExpectAndReturn(sock_desc, cmock_retval) connectToServer_CMockExpectAndReturn(__LINE__, sock_desc, cmock_retval)
void connectToServer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* sock_desc, int cmock_to_return);

#endif
