net.h
PROTOCOL_TYPE
Referenced by main.
int readSocket(int sock, char recvline[])
sock recvline invalid_status Read from Socket
References MAX_MSG_LEN.
Referenced by main, connection_handler.
int writeSocket(int sock, char sendline[])
sock sendline invalid_status Write to socket
References MAX_MSG_LEN.
Referenced by main, connection_handler.
int connectToServer(void *sock_desc)
sock_desc invalid_status Connect to Sever
References SRV_PORT, SRV_ADDR.