net.c
int readSocket(int sock, char recvline[])
Read from Socket
References MAX_MSG_LEN.
Referenced by main, connection_handler.
int writeSocket(int sock, char sendline[])
Write to socket
References MAX_MSG_LEN.
Referenced by main, connection_handler.
int connectToServer(void *sock_desc)
Connect to Sever
References SRV_PORT, SRV_ADDR.