sensors.h
uint16_t getSensorReadingStr(eSensor s, char buffer[])
helper - gets a measurement s buffer invalid_status helper - gets a measurement
References brightness, brightness_str.
Referenced by buildRequestXML.
int newMeasurement(eSensor s)
helper - sets a random measurement value s invalid_status helper - sets a random measurement value
References battery, brightness, max_brightness_levels, humidity, noise, personsPassed, Reading_t::value, temperature.
Referenced by generateMeasurements.
uint16_t generateMeasurements(void)
helper - loop to generate measurements invalid_status helper - loop to generate measurements
References max_sensors, Reading_t::value, newMeasurement, Reading_t::elapsed, Reading_t::interval.
Referenced by main.