server.h
void* connection_handler(void *)
new connection handler socket fd
References MAX_MSG_LEN, readSocket, buildReplyXML, writeSocket.
Referenced by main.
void shutdownHandler(int s)
handler for service shutdown s signal shutdown handler to write config
References socket_desc, writeConfig, exitHandler.
Referenced by main.
void exitHandler()
Unused
Referenced by shutdownHandler.