xml.h
uint16_t buildReplyXML(char recvline[], char sendline[], size_t read_size)
Builds XML recvline sendline read_size invalid_status Build Server reply XML
References max_sensors, sensor_str, Reading_t::value, MAX_MSG_LEN.
Referenced by connection_handler.
uint16_t buildRequestXML(eRequest req, char sendline[])
builds a client xml request (update/retrieve) req sendline invalid_status builds a client xml request (update/retrieve)
References request_str, max_sensors, configure, getSensorReadingStr, sensor_str, MAX_MSG_LEN.
Referenced by main, writeConfig.
int writeConfig()
Save readings to file invalid_status Save readings to file
References MAX_MSG_LEN, buildRequestXML, configure.
Referenced by shutdownHandler.
int readConfig()
Load Reading from file invalid_status Load Reading from file
References max_sensors, sensor_str, Reading_t::value.
Referenced by main.